GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###
GET localhost:8080/number/next

###

GET localhost:8080/number/next

###

GET localhost:8080/number/random
